sh ./generate_run.sh -s attr:resource=$1,unit=$2
sh ./generate_run.sh -s coll:resource=$1,unit=$2
sh ./generate_run.sh -s comm:resource=$1,unit=$2
sh ./generate_run.sh -s datatype:resource=$1,unit=$2
sh ./generate_run.sh -s errhan:resource=$1,unit=$2
sh ./generate_run.sh -s group:resource=$1,unit=$2
sh ./generate_run.sh -s info:resource=$1,unit=$2
sh ./generate_run.sh -s init:resource=$1,unit=$2
sh ./generate_run.sh -s mpi_t:resource=$1,unit=$2
sh ./generate_run.sh -s pt2pt:resource=$1,unit=$2
sh ./generate_run.sh -s rma:resource=$1,unit=$2
sh ./generate_run.sh -s topo:resource=$1,unit=$2
sh ./generate_run.sh -s perf:resource=$1,unit=$2
##sh ./generate_run.sh -s io:resource=$1,unit=$2
sh ./generate_run.sh -s errors:resource=$1,unit=$2
sh ./generate_run.sh -s impls:resource=$1,unit=$2
