.PHONY: all

all:
	@echo "make summary, make list, or make batch"
summary:
	sh SUMMARY.sh
list:
	sh CREATE_LIST.sh
numazu-batch:
	sh CREATE_BATCH.sh dvsys-spack2 rscunit_ft02
fugaku-batch:
	sh CREATE_BATCH.sh dvsys-sin rscunit_ft01
