#!/bin/bash
DIR=$1
INSTDIR=${DIR:-$HOME/mpich-tofu}
LIBFABRIC_SRC=./libfabric.sock
export LD_LIBRARY_PATH=${INSTDIR}/lib
LOGDIR=log

case `hostname` in
    ea-login01)
	#export CC=/opt/FJSVxtclanga/tcsds-1.1.7/bin/fccpx
	export RANLIB=/opt/FJSVxos/devkit/aarch64/bin/aarch64-linux-gnu-ranlib
	export CC=/opt/FJSVxos/devkit/aarch64/bin/aarch64-linux-gnu-gcc
	export LD=/opt/FJSVxos/devkit/aarch64/bin/aarch64-linux-gnu-ld
##	export LDFLAGS="-L/opt/FJSVxos/devkit/aarch64/aarch64-linux-gnu/lib64 -L/opt/FJSVxtclanga/tcsds-1.1.7/lib64 -L/opt/FJSVxos/devkit/aarch64/rfs/usr/lib64 -L$LD_LIBRARY_PATH -L$INSTDIR/lib"
	export LDFLAGS="-L$LD_LIBRARY_PATH -L/opt/FJSVxos/devkit/aarch64/rfs/usr/lib64"
	XX_CONF_HOST=--host=aarch64-unknown-linux-gnu
	export LIBS="-ltofutop -ltofucom -ldl"
	export CPPFLAGS="-I/opt/FJSVxos/devkit/aarch64/rfs/usr/include/FJSVtcs/ple/"
	#export CPPFLAGS="-DFX100 -DTOFU_SIM_BUG"
	CONFIG_OPTIONS="--disable-psm \
	--disable-psm2 \
	--enable-sockets \
	--disable-verbs \
	--disable-usnic \
	--disable-mlx \
	--disable-gni \
	--enable-udp \
	--disable-rxm \
	--disable-rxd \
	--enable-debug \
	--disable-bgq"
	;;
    fh01p04)
	XX_CONF_HOST=--host=sparc64-unknown-linux-gnu
	GCC_HOME=/opt/FJSVXosDevkit/sparc64fx/V02L01E07
	export CC=$GCC_HOME/bin/gccpx
	export LD=$GCC_HOME/bin/ldpx
	export LDFLAGS="-shared-libgcc -L/opt/FJSVpxtof/sparc64fx/lib64 -L$INSTDIR/lib"
	export LIBS="-lutofu -ltofutop -ltofucom -ldl"
	export CPPFLAGS="-DFX100 -DTOFU_SIM_BUG"
	CONFIG_OPTIONS="--disable-psm \
	--disable-psm2 \
	--disable-sockets \
	--disable-verbs \
	--disable-usnic \
	--disable-mlx \
	--disable-gni \
	--disable-udp \
	--disable-rxm \
	--disable-rxd \
	--enable-debug \
	--disable-bgq"
	;;
    *)
	CONFIG_OPTIONS="--enable-mrail=no \
	--enable-sockets \
	--enable-rxm=no \
	--enable-rxd=no \
	--enable-rstream=no \
	--disable-direct \
	--disable-verbs \
	--disable-bgq \
	--enable-debug \
	--without-valgrind"
	export CC=gcc
	export LD=ld
	export LDFLAGS="-L$LD_LIBRARY_PATH"
##	export LIBS="-lutofu"
	export LIBS="-ltofucom -ltofutop"
	export CPPFLAGS="-DTOFU_NEWSIM_BUG"
	;;
esac

if [ ! -d $LOGDIR ]; then
    mkdir $LOGDIR
fi

echo CPPFLAGS=$CPPFLAGS
echo LDFLAGS=\"$LDFLAGS\"
echo LIBS=$LIBS
echo XX_CONF_HOST=$XX_CONF_HOST

date
(cd $LIBFABRIC_SRC; ./configure \
	$XX_CONF_HOST \
	--prefix=$INSTDIR \
	$CONFIG_OPTIONS \
	--enable-tofu=yes \
	--enable-shared \
	>../$LOGDIR/cnf-libfabric-sock.txt 2>&1)
date
