#!/bin/bash
OPTION=$1
DIR=$2
INSTDIR=${DIR:-$HOME/mpich-tofu}
MPICH_SRC=./mpich
LOGDIR=log
CUR_DIR=`pwd`
export LD_LIBRARY_PATH=$INSTDIR/lib:$LD_LIBRARY_PATH

export LIBS="-ldl -lrt -ltofutop -ltofucom -lpmix -lfabric"
###export LIBS="-ldl -lrt -ltofutop -ltofucom -lpmix-wrap -lfabric"
case `hostname` in
    fn01sv*|ea-login01)
	export LIBS="-ldl -lrt -ltofutop -ltofucom -lpmix -lfabric -lutf"
	export CC=/opt/FJSVxos/devkit/aarch64/bin/aarch64-linux-gnu-gcc
	export CXX=/opt/FJSVxos/devkit/aarch64/bin/aarch64-linux-gnu-g++
	export LD=/opt/FJSVxos/devkit/aarch64/bin/aarch64-linux-gnu-ld
	export CPPFLAGS=-I/opt/FJSVxos/devkit/aarch64/rfs/usr/include/FJSVtcs/ple
	# export LDFLAGS="-L/opt/FJSVxos/devkit/aarch64/aarch64-linux-gnu/lib64 -L/opt/FJSVxtclanga/tcsds-1.1.7/lib64 -L/opt/FJSVxos/devkit/aarch64/rfs/usr/lib64 -L$LD_LIBRARY_PATH -L$INSTDIR/lib"
	export LDFLAGS="-L$INSTDIR/lib"
	XX_CONF_HOST=--host=aarch64-unknown-linux-gnu
	XX_CONF_PMIX="--with-pmix=/opt/FJSVxos/devkit/aarch64/rfs/usr/lib/FJSVtcs/ple/lib64 --with-pmix-include=/opt/FJSVxos/devkit/aarch64/rfs/usr/include/FJSVtcs/ple --with-pm=no";;

    fh01p04)
	GCC_HOME=/opt/FJSVXosDevkit/sparc64fx/V02L01E07
	export CC=$GCC_HOME/bin/gccpx
	export LD=$GCC_HOME/bin/ldpx
	export LDFLAGS="-shared-libgcc -L/opt/FJSVpxtof/sparc64fx/lib64 -L$LD_LIBRARY_PATH"
	XX_CONF_HOST=--host=sparc64-unknown-linux-gnu
	XX_CONF_PMIX="--with-pmix=$INSTDIR --with-pm=no";;
    *)
	export CC=gcc
	export LD=ld
	export LDFLAGS="-Wl,-rpath -Wl,$LD_LIBRARY_PATH"
	XX_CONF_HOST=
	XX_CONF_PMIX="--with-pmix=$INSTDIR --with-pm=no";;
##	XX_CONF_PMIX=--with-pm=hydra:gforker
esac

echo CC=$CC
echo LD=$LD
echo LDFLAGS=$LDFLAGS
echo LD_LIBRARY_PATH=$LD_LIBRARY_PATH
echo INSTDIR=$INSTDIR
echo LIBS=$LIBS

if [ ! -d $LOGDIR ]; then
    mkdir $LOGDIR
fi

# debug|perf|perf-hack
case $OPTION in
    debug)
	echo "DEBUG MODE"
	XX_CONF_PERF_ARGS=" \
		--enable-error-checking=all \
		--enable-error-messages=all \
		--enable-g=all \
		--enable-fast=O0 \
		--enable-mpit-pvars=all \
		--enable-timing=runtime \
		--enable-threads=runtime \
	"
	;;
    normal)
	echo "NORMAL"
	XX_CONF_PERF_ARGS=" \
		--enable-error-checking=runtime \
		--enable-error-messages=generic \
		--enable-g=most \
		--enable-fast=none \
		--enable-mpit-pvars=all \
		--enable-timing=runtime \
		--enable-threads=runtime \
	"
	;;
    perf|performance)
	echo "PERFORMANCE"
	XX_CONF_PERF_ARGS=" \
		--enable-error-checking=no \
		--enable-error-messages=generic \
		--enable-g=none \
		--enable-fast=all \
		--enable-mpit-pvars=none \
		--enable-timing=none \
		--enable-threads=runtime \
	"
	;;
    perf-hack)
	echo "PERFORMANCE HACK"
	XX_CONF_PERF_ARGS=" \
		--enable-error-checking=no \
		--enable-error-messages=none \
		--enable-g=none \
		--enable-fast=all \
		--enable-mpit-pvars=none \
		--enable-timing=none \
		--enable-threads=runtime \
	"
	;;
    *)
	echo "DISABLE-FAST"
	XX_CONF_PERF_ARGS="--disable-fast \
		--enable-g=dbg,log \
	"
	;;
esac

# --disable-static

which gcc
date
(cd $MPICH_SRC; export ac_cv_func_malloc_0_nonnull=yes; ./configure \
	$XX_CONF_HOST \
	--enable-threads=single \
	--config-cache \
	--prefix=${INSTDIR} \
	--enable-shared \
	\
	--enable-fortran=no \
	--enable-cxx \
	--enable-romio=no \
	\
	--with-mpl-prefix=embedded \
	--with-openpa-prefix=embedded \
	--with-hwloc-prefix=embedded \
	--with-device=ch4:ofi \
	$XX_CONF_PMIX \
	\
	$XX_CONF_PERF_ARGS \
	\
	--with-libfabric-include=$CUR_DIR/libfabric/include	\
 	--with-libfabric-lib=$INSTDIR/lib	\
	\
	--enable-ch4-direct=netmod \
	\
	--enable-debug \
	--disable-direct \
	--with-wrapper-dl-type=none \
	MPICHLIB_CFLAGS=-O3 MPICHLIB_FFLAGS=-O3 MPICHLIB_CXXFLAGS=-O3 MPICHLIB_FCFLAGS="-g -O1" MPICH_MPICC_LIBS="-lpmix -ldl -lrt -ltofutop -ltofucom -lfabric" \
	MPICH_MPICXX_LIBS="-lpmix -ldl -lrt -ltofutop -ltofucom -lfabric" \
	MPICH_MPIF77_LIBS="-lpmix -ldl -lrt -ltofutop -ltofucom -lfabric" \
	>../$LOGDIR/cnf-mpi.txt 2>&1)

#(cd ${MPICH_SRC}; make clean >/dev/null)
#(cd ${MPICH_SRC}; make install >../ins-mpi.txt 2>&1)
date

exit 0

##	--with-libfabric=embedded \
##
